---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu_12_04
    image: ubuntu-upstart:12.04
  - name: ubuntu_14_04
    image: ubuntu-upstart:14.04
  - name: ubuntu_16_04
    image: solita/ubuntu-systemd:16.04
    privileged: True    
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
